import React from "react";
import "./MiniDetalleListado.css"


let cursos = [
    // {
    //   id: 1,
    //   titulo: 'Metodologias agiles:scrum',
    //   categoria: 'organizacion',
    //   precio: 1500,
    //   imagen_principal: './imagenes/cursos-online.jpg',
    //   profesor: 'Eddy Ficio',
    //   descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    //   titulo_2: 'hola que hace',
    //   descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    //   temario_modulos: 2,
    //   temario_clases: 45,
    //   temario_duracion_total: '3h 52m',
    //   comentarios: 100,
    //   positivas: 90,
    //   pregunta_1_titulo: 'Como se llama el profe?',
    //   'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    //   'pregunta-2_titulo': 'Como se va a dar clases',
    //   respuesta: 'con toda la onda',
    //   'pregunta-3_titulo': 'ya no se que mas poner',
    //   'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    // },
    {
      id: 2,
      titulo: 'Fotografia profesional',
      categoria: 'multimedia',
      precio: 1500,
      imagen_principal: './imagenes/camera.jpg',
      profesor: 'Esteban Quito',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    },
    {
      id: 3,
      titulo: 'Bordado a mano nivel 1',
      categoria: 'manualidades',
      precio: 1500,
      profesor: 'Jhony Laburo',
      imagen_principal: './imagenes/bordado.jpg',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    },
    {
      id: 4,
      titulo: 'Tragos con y sin alcohol',
      categoria: 'alimentos',
      precio: 1500,
      imagen_principal: './imagenes/drink.jpg',
      profesor: 'Lali Cuadora',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    },
    {
      id: 5,
      titulo: 'Costura para modistas',
      categoria: 'manualidades',
      precio: 1500,
      imagen_principal: './imagenes/costura.jpg',
      profesor: 'Elsa Capuntas',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    },
    {
      id: 6,
      titulo: 'Preparación de discursos y exposiciones',
      categoria: 'liderazgo',
      precio: 1500,
      imagen_principal: './imagenes/ted-talk.jpg',
      profesor: 'Armando Paredes',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    },
    {
      id: 7,
      titulo: 'Preparación de clases virtuales',
      categoria: 'multimedia',
      precio: 1500,
      imagen_principal: './imagenes/virtualidad.jpg',
      profesor: 'Carlitos Tado',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    },
    {
      id: 8,
      titulo: 'Técnicas básicas con acuarela',
      categoria: 'manualidades',
      precio: 1500,
      imagen_principal: './imagenes/watercolor.jpg',
      profesor: 'Elga Tito',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    },
    {
      id: 9,
      titulo: 'Autorretratos fotográficos',
      categoria: 'multimedia',
      precio: 1500,
      imagen_principal: './imagenes/selfie.jpg',
      profesor: 'Inés Tornudo',
      'imagen-1': 'imagen_2.jpg',
      'imagen-2': 'cursos-en-linea.jpg',
      'imagen-3': 'cursos-online.jpeg',
      descripcion_corta: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      titulo_2: 'hola que hace',
      descripcion_larga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      temario_modulos: 2,
      temario_clases: 45,
      temario_duracion_total: '3h 52m',
      'titulo_int-1': 'conceptos generales',
      'titulo_int-2': 'conociendo herramientas principales',
      'titulo_int-3': 'Proyecto final',
      'titulo_p1-1': 'Lo que corresponda',
      'titulo_p1-2': 'Algo va aca',
      'titulo_p1-3': 'Aca tambien va algo',
      'titulo_p2-1': 'Avanzando',
      'titulo_p2-2': 'Avanzando con onda',
      'titulo_p2-3': 'Ya terminamos, vuelva prontos',
      alumnos: 500,
      comentarios: 100,
      positivas: 90,
      pregunta_1_titulo: 'Como se llama el profe?',
      'pregunta_1_respuesta-1': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'pregunta-2_titulo': 'Como se va a dar clases',
      respuesta: 'con toda la onda',
      'pregunta-3_titulo': 'ya no se que mas poner',
      'pregunta-3_respuesta': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    }
  ]

function MiniDetalleListado (){


    return (
            <div className="MDL-MaxBox">
                {
                    cursos.map((curso,i)=> {
                        return(
                            <div className="MDL-contenedor">
                                <div className="MDL-foto">
                                    <img className="MDL-imagen" src={ cursos[i].imagen_principal } alt="imagen curso"></img>
                                </div>
                                <div className="MDL-contenedor-info">
                                    <h1 className="MDL-titulo">
                                        {cursos[i].titulo}
                                    </h1>
                                    <p className="MDL-parrafo">
                                        {cursos[i].descripcion_corta}
                                    </p>
                                </div>
                            </div>
                        )
                    })
                }
            </div>
    );
}

export default MiniDetalleListado;